//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Pasport { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string Position { get; set; }
        public Nullable<long> Inn { get; set; }
        public string Snils { get; set; }
        public int IdUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
